"""Structural tests for mcp_server/Dockerfile.

These tests validate that the Dockerfile maintains critical properties
required for reproducible builds and correct dependency installation.
"""

from __future__ import annotations

from pathlib import Path

import pytest

DOCKERFILE = Path(__file__).resolve().parents[2] / "mcp_server" / "Dockerfile"


@pytest.fixture(scope="module")
def dockerfile_text() -> str:
    return DOCKERFILE.read_text(encoding="utf-8")


class TestPoetryPinned:
    """Poetry version must be pinned to match the lock file generation version."""

    def test_poetry_pinned_to_232(self, dockerfile_text: str) -> None:
        assert "poetry==2.3.2" in dockerfile_text, (
            "Dockerfile must pin poetry==2.3.2 (lock was generated by Poetry 2.3.2)"
        )


class TestLockCopied:
    """poetry.lock must be copied into the image before poetry install."""

    def test_lock_copy_exists(self, dockerfile_text: str) -> None:
        assert "poetry.lock" in dockerfile_text, (
            "Dockerfile must contain COPY of poetry.lock"
        )

    def test_lock_copied_before_install(self, dockerfile_text: str) -> None:
        lock_pos = dockerfile_text.find("poetry.lock")
        install_pos = dockerfile_text.find("poetry install")
        assert lock_pos < install_pos, (
            "poetry.lock must be copied BEFORE poetry install"
        )


class TestPyprojectCopied:
    """pyproject.toml must be copied into the image."""

    def test_pyproject_copy_exists(self, dockerfile_text: str) -> None:
        assert "pyproject.toml" in dockerfile_text


class TestNoWorkaround:
    """Dockerfile must not contain pip install openpyxl as a workaround."""

    def test_no_pip_install_openpyxl(self, dockerfile_text: str) -> None:
        assert "pip install" not in dockerfile_text or "openpyxl" not in dockerfile_text, (
            "Dockerfile must not use 'pip install openpyxl' as a workaround"
        )


class TestPreservedProperties:
    """Properties that must NOT change in this fix."""

    def test_base_image(self, dockerfile_text: str) -> None:
        assert "FROM python:3.12-slim" in dockerfile_text

    def test_cmd(self, dockerfile_text: str) -> None:
        assert 'CMD ["python", "-m", "mcp_server.server"]' in dockerfile_text

    def test_expose(self, dockerfile_text: str) -> None:
        assert "EXPOSE 8005" in dockerfile_text

    def test_install_flags(self, dockerfile_text: str) -> None:
        assert "--no-interaction" in dockerfile_text
        assert "--no-ansi" in dockerfile_text
        assert "--only=main" in dockerfile_text
        assert "--no-root" in dockerfile_text

    def test_domain_copy(self, dockerfile_text: str) -> None:
        assert "COPY domain/" in dockerfile_text
