services:
  math_tool:
    build:
      context: ./calc
      dockerfile: mathtool.Dockerfile
    image: math_tool_custom:0.1.0
    container_name: math_tool
    restart: always
    ports:
      - "8001:8001"

  mcp_server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    image: pi_mcp_server:0.1.0
    container_name: mcp_server
    restart: always
    ports:
      - "8005:8005"
    env_file:
      - ./mcp_server/.env
    environment:
      - MCP_PORT=8005

  agent_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: agent_bot:0.2.0
    container_name: agent_bot
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - ./app/.env
    environment:
      - LLM_PROVIDER=ollama
      - MCP_SERVER_URL=http://mcp_server:8005/mcp
      - MATH_TOOL_BASE_URL=http://math_tool:8001
      - PHOENIX_ENABLED=true
      - PHOENIX_PROJECT_NAME=pi-chat-api
      - PHOENIX_COLLECTOR_ENDPOINT=http://10.247.179.197:6006/v1/traces
    depends_on:
      - math_tool
      - mcp_server

  agent_bot_chat_bridge:
    image: agent_bot:0.2.0
    container_name: agent_bot_chat_bridge
    restart: always
    command: python -m app.bridge.google_chat.worker --send
    env_file:
      - ./app/.env
    environment:
      - AGENT_INTERNAL_URL=http://agent_bot:8002/chat
      - GOOGLE_APPLICATION_CREDENTIALS=./secrets/chat_secret.json
      - PYTHONUNBUFFERED=1
    volumes:
      - ./secrets:/app/secrets:ro
    depends_on:
      - agent_bot