from __future__ import annotations

from enum import Enum


class ValidationErrorCode(str, Enum):
    INVALID_GROUP_BY = "INVALID_GROUP_BY"
    INVALID_DATA_METHOD = "INVALID_DATA_METHOD"
    INVALID_ARGUMENT_COMBINATION = "INVALID_ARGUMENT_COMBINATION"
    INVALID_TIME_EXPRESSION = "INVALID_TIME_EXPRESSION"
    INVALID_TIME_WINDOW = "INVALID_TIME_WINDOW"
    UNSUPPORTED_TIME_EXPRESSION = "UNSUPPORTED_TIME_EXPRESSION"
    TIME_RESOLUTION_ERROR = "TIME_RESOLUTION_ERROR"
    INVALID_DATA_METHOD_FOR_AGGREGATED_SERIES = "INVALID_DATA_METHOD_FOR_AGGREGATED_SERIES"
    INTERVAL_NOT_ALLOWED = "INTERVAL_NOT_ALLOWED"
    INTERVAL_REQUIRED = "INTERVAL_REQUIRED"
    INVALID_INTERVAL = "INVALID_INTERVAL"
    ESTIMATED_ROW_LIMIT_EXCEEDED = "ESTIMATED_ROW_LIMIT_EXCEEDED"
    UNSUPPORTED_POINT_TYPE_FOR_METHOD = "UNSUPPORTED_POINT_TYPE_FOR_METHOD"
    SUMMARY_DURATION_GROUP_BY_MISMATCH = "SUMMARY_DURATION_GROUP_BY_MISMATCH"
    ARTIFACT_ROW_LIMIT_EXCEEDED = "ARTIFACT_ROW_LIMIT_EXCEEDED"
    ARTIFACT_SIZE_LIMIT_EXCEEDED = "ARTIFACT_SIZE_LIMIT_EXCEEDED"
    SERIES_PAGINATION_INCOMPLETE = "SERIES_PAGINATION_INCOMPLETE"
    PI_SERIES_QUERY_ERROR = "PI_SERIES_QUERY_ERROR"
    ARTIFACT_BUILD_ERROR = "ARTIFACT_BUILD_ERROR"
    ARTIFACT_UPLOAD_ERROR = "ARTIFACT_UPLOAD_ERROR"
    INTERNAL_SERIES_EXPORT_ERROR = "INTERNAL_SERIES_EXPORT_ERROR"
    MISSING_TAG = "MISSING_TAG"
    MISSING_TAGS = "MISSING_TAGS"
    TOO_MANY_TAGS = "TOO_MANY_TAGS"
    WINDOW_EXCEEDS_MAX = "WINDOW_EXCEEDS_MAX"
    INVALID_TIMESTAMP = "INVALID_TIMESTAMP"
    TAG_NOT_FOUND = "TAG_NOT_FOUND"
    PI_TIMEOUT = "PI_TIMEOUT"
    PI_AUTH_ERROR = "PI_AUTH_ERROR"
    NO_DATA_IN_WINDOW = "NO_DATA_IN_WINDOW"
    INVALID_DIGITAL_SET = "INVALID_DIGITAL_SET"
    UNSUPPORTED_POINT_TYPE = "UNSUPPORTED_POINT_TYPE"
    PI_RESPONSE_INVALID = "PI_RESPONSE_INVALID"
    INVALID_ZERO_POLICY = "INVALID_ZERO_POLICY"


class DomainValidationError(ValueError):
    def __init__(self, code: ValidationErrorCode, message: str) -> None:
        self.code = code
        super().__init__(message)
